steps:
  # Debug: Print substitution variable length (not the actual value for security)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "=== Debug ===" && echo "API key length: $(echo -n "$$VITE_KEY" | wc -c)" && echo "First 4 chars: $(echo "$$VITE_KEY" | cut -c1-4)"'
    env:
      - 'VITE_KEY=$_VITE_GEMINI_API_KEY'
    id: 'Debug'

  # Étape 1 : Construire l'image Docker en passant la clé API
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY'
      - '.'
    id: 'Build'

  # Étape 2 : Pousser l'image vers le registre Google
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: 'Push'

  # Étape 3 : Déployer sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: 'Deploy'

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

# Définition des variables que l'on va régler dans la console Google
substitutions:
    _SERVICE_NAME: cardgenerator # <--- Vérifiez que c'est bien le nom de votre service Cloud Run
    _DEPLOY_REGION: europe-west9 # <--- Vérifiez votre région (visible dans l'URL de votre app)